### PR TITLE
Use PythonOT

### LINKED ISSUE #42: Separate Python even more?
I am implementing a Python interface for one of my packages with pyjulia. The package depends on OptimalTransport but since POT was quite annoying to install (there's a bug in pip and therefore one always has to install cython and numpy first, otherwise installation will fail) I completely switched to OptimalTransport + Tulip, eliminating all Python dependencies. However, pyjulia requires PyCall and installs and loads it automatically, and therefore automatically also the POT submodule in OptimalTransport is loaded even though I don't want to use it. And now Python users either have to install POT which is quite annoying and also problematic for CI (and it's not even used at all!), or they'll get an error message when OptimalTransport tries to load it in https://github.com/zsteve/OptimalTransport.jl/blob/9ad8f733770b7cd446c84ebfc90e2a558d6d120b/src/pot.jl#L8.

Maybe the Python interface to POT could be moved to a completely separate package or one could require users to load, and possibly install, it explicitly by making the `__init__` function a proper function that could be called e.g. `load_POT!`.

### PR DESCRIPTION
**Pull request by devmotion**
This PR removes the Python interface from the package and instead uses PythonOT in the tests. I couldn't find a way to remove the submodule in a non-breaking way since we don't want to make PyCall or PythonOT a non-optional dependency now but optional fallbacks would require that users have already installed PythonOT which defeats the purpose.

Fixes https://github.com/JuliaOptimalTransport/OptimalTransport.jl/issues/42.

### CODE REVIEW

**Comment by devmotion** [comment]
It took a while but now all tests pass: I simplified the CI tests and removed the manual installation of Python and POT (handled by Conda.jl now) but this caused test failures. I fixed these numerical issues by increasing the maximum number of iterations and adjusting tolerances in POT. I also used the opportunity to add tests for Julia 1.0 which uncovered some bugs.

**Comment by devmotion** [comment]
I separated the changes related to Julia 1.0, the remaining changes are all related to PythonOT and testing with Conda.jl.

**Comment by zsteve** [comment]
> It took a while but now all tests pass: I simplified the CI tests and removed the manual installation of Python and POT (handled by Conda.jl now) but this caused test failures. I fixed these numerical issues by increasing the maximum number of iterations and adjusting tolerances in POT. I also used the opportunity to add tests for Julia 1.0 which uncovered some bugs.

Did these numerical issues arise from changing the route of installation of POT? Strange

**Review by zsteve — APPROVED** [review]

**Comment by devmotion** [comment]
> Did these numerical issues arise from changing the route of installation of POT? Strange

I think it might be also due to different Python versions - previously we installed a specific version explicitly whereas now just the default miniconda Python version of Conda.jl is used.

**Pull request merged**
